"""Initial migration

Revision ID: 467266827bbd
Revises: 
Create Date: 2026-03-18 20:05:39.872100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '467266827bbd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumnos_entrenamiento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alumnos_entrenamiento_liga_id'), ['liga_id'], unique=False)

    with op.batch_alter_table('arbitros', schema=None) as batch_op:
        batch_op.alter_column('foto_url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_arbitros_liga_id'), ['liga_id'], unique=False)

    with op.batch_alter_table('asistencias_partido', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asistencias_partido_liga_id'), ['liga_id'], unique=False)

    with op.batch_alter_table('canchas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_canchas_liga_id'), ['liga_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('canchas_dueno_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['dueno_id'], ['id'])

    with op.batch_alter_table('equipos', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('equipos_uid_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_equipos_liga_id'), ['liga_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_equipos_uid'), ['uid'], unique=True)

    with op.batch_alter_table('eventos_partido', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_eventos_partido_liga_id'), ['liga_id'], unique=False)

    with op.batch_alter_table('grupos_entrenamiento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grupos_entrenamiento_liga_id'), ['liga_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('grupos_entrenamiento_profesor_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'arbitros', ['profesor_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('inscripciones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inscripciones_liga_id'), ['liga_id'], unique=False)

    with op.batch_alter_table('jugadores', schema=None) as batch_op:
        batch_op.alter_column('seudonimo',
               existing_type=sa.VARCHAR(length=18),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_jugadores_liga_id'), ['liga_id'], unique=False)
        batch_op.drop_column('edad')

    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pagos_liga_id'), ['liga_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pagos_torneo_id'), ['torneo_id'], unique=False)

    with op.batch_alter_table('pagos_canchas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pagos_canchas_liga_id'), ['liga_id'], unique=False)

    with op.batch_alter_table('partidos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_partidos_liga_id'), ['liga_id'], unique=False)
        batch_op.create_foreign_key(None, 'equipos', ['ganador_id'], ['id'])

    with op.batch_alter_table('torneos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_torneos_liga_id'), ['liga_id'], unique=False)

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('rol',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('rol',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('torneos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_torneos_liga_id'))

    with op.batch_alter_table('partidos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_partidos_liga_id'))

    with op.batch_alter_table('pagos_canchas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pagos_canchas_liga_id'))

    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pagos_torneo_id'))
        batch_op.drop_index(batch_op.f('ix_pagos_liga_id'))

    with op.batch_alter_table('jugadores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edad', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_jugadores_liga_id'))
        batch_op.alter_column('seudonimo',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=18),
               existing_nullable=True)

    with op.batch_alter_table('inscripciones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inscripciones_liga_id'))

    with op.batch_alter_table('grupos_entrenamiento', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('grupos_entrenamiento_profesor_id_fkey'), 'arbitros', ['profesor_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_grupos_entrenamiento_liga_id'))

    with op.batch_alter_table('eventos_partido', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_eventos_partido_liga_id'))

    with op.batch_alter_table('equipos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_equipos_uid'))
        batch_op.drop_index(batch_op.f('ix_equipos_liga_id'))
        batch_op.create_unique_constraint(batch_op.f('equipos_uid_key'), ['uid'])

    with op.batch_alter_table('canchas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('canchas_dueno_id_fkey'), 'usuarios', ['dueno_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_index(batch_op.f('ix_canchas_liga_id'))

    with op.batch_alter_table('asistencias_partido', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asistencias_partido_liga_id'))

    with op.batch_alter_table('arbitros', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_arbitros_liga_id'))
        batch_op.alter_column('foto_url',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    with op.batch_alter_table('alumnos_entrenamiento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alumnos_entrenamiento_liga_id'))

    # ### end Alembic commands ###
